### ISSUE TITLE
Tracker NullReferenceException when doing Power of Mist check

### ISSUE THREAD

**Issue by RefinedHornet** [TalicZealot/SotnRandoTools#11] opened 2021-05-15 21:43 UTC
[Tracker-Power-of-Mist-Bug-SaveRAM.zip](https://github.com/TalicZealot/SotnRandoTools/files/6488289/Tracker-Power-of-Mist-Bug-SaveRAM.zip)

# Error:
If an error popped up paste a screenshot of it or the error message.
System.NullReferenceException: Object reference not set to an instance of an object.
   at SotnRandoTools.RandoTracker.Tracker.ClearMapLocation(Int32 index)
   at SotnRandoTools.RandoTracker.Tracker.CheckRooms(WatchList watchlist)
   at SotnRandoTools.RandoTracker.Tracker.UpdateLocations()
   at SotnRandoTools.RandoTracker.Tracker.Update()
   at SotnRandoTools.ToolMainForm.UpdateValues(ToolFormUpdateType type)
   at BizHawk.Client.EmuHawk.ToolManager.UpdateToolsAfter()
   at BizHawk.Client.EmuHawk.MainForm.StepRunLoop_Core(Boolean force)
   at BizHawk.Client.EmuHawk.MainForm.ProgramRunLoop()
   at BizHawk.Client.EmuHawk.Program.SubMain(String[] args)

# Bug description:
Approaching the Power of Mist check from the side or from under with a gravity jump causes a NullReferenceException.

# How to reproduce:
Open the Castle Keep save on the attached virtual memory card and go near the Power of Mist check.

# Additional context or screenshot:
https://www.twitch.tv/videos/1024016988

# BizHawk version:
2.6.1

# Seed Information:
Link to the ppf: https://cdn.discordapp.com/attachments/566486385377280001/843200882538577970/SotN-Randomizer_SurprisingAxelord14.ppf

# Randomizer version:
3.5.17

# Operating system and version:
Windows 7 6.1.7601 Service Pack 1 Build 7601

**Comment by TalicZealot** [comment] 2021-05-15 23:30
Was caused by outdated files due to skipping versions with the Updater. Will be fixed for future releases.

**Closed by TalicZealot** 2021-05-15 23:30 UTC
Labels: bug
